---
title: "Distribution of Q. pyrenaica forests "
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: rows
---

```{r setup, include=FALSE}
library('flexdashboard')
```

```{r pacakges, message=FALSE, warning=FALSE}
library('rgdal')
library("leaflet") 
library("sp")
library("sf")
library("raster")
library("dplyr")
library("here")
library("mapview")
library("maptools")
```


```{r readData}
machine <- 'ajpelu' 
machine <- 'ajpeluLap' 

di <- here() 

# Read spatial data 
qp <- rgdal::readOGR(dsn=paste0(di,'/data/dist_robledal/'),
                     layer = 'q_pyr_sn_4326', verbose = FALSE, encoding = "UTF-8")

### --- Read limits of Sierra Nevada Protected area
mydsn = paste0('/Users/', machine, '/Google Drive/carto_public/EENNPP/InfGeografica/InfVectorial/Shapes/ED50_30')
enp <- readOGR(dsn=mydsn, layer = 'EENNPP', encoding="UTF-8", verbose = FALSE)

proj4string(enp) <- CRS("+init=epsg:23030")

# Sierra Nevada limits 
enp_r <- spTransform(enp, CRS("+init=epsg:4326"))

# Select Sierra Nevada 
sn <- subset(enp_r, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Espacio Natural')
sn_nat <- subset(enp_r, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Parque Nacional')
```




```{r}
# Irrigation channel
acequias <- rgdal::readOGR(dsn=paste0(di, '/data/acequias/'),
                           layer = 'acequias_pn_snevada', verbose = FALSE,
                           encoding = 'UTF-8') 

acequias_r <- spTransform(acequias, crs(enp_r))
```

```{r}
# BBDD Forestal
forestal <- rgdal::readOGR(dsn=paste0(di, '/data/bbdd_forestal/'),
                           layer = 'proy_forestales', verbose = FALSE,
                           encoding = 'UTF-8') 
proj4string(forestal) <- CRS("+init=epsg:23030")

forestal_r <- spTransform(forestal, crs(enp_r))
```


```{r}
# Read modis iv pixels
modis_iv <- rgdal::readOGR(dsn=paste0(di, '/data/ndvi_modis/'),
                     layer = 'iv_malla_modis_qp_pol', verbose = FALSE, encoding = "UTF-8")
```

```{r}
# Incendios 

## Histórico REDIAM 1975 - 2016 
# http://www.juntadeandalucia.es/medioambiente/site/rediam/menuitem.04dc44281e5d53cf8ca78ca731525ea0/?vgnextoid=d07e1cd522a3d310VgnVCM2000000624e50aRCRD&vgnextchannel=1bff7d087270f210VgnVCM1000001325e50aRCRD 

fires_raw <- rgdal::readOGR(dsn=paste0(di, '/data/incendios/rediam/'),
                     layer = 'incendios_historico', verbose = FALSE, encoding = "UTF-8")
fires <- spTransform(fires_raw, crs(enp_r))

# WMS REDIAM
# http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_historico_incendios?   
# http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_historico_areas_recorridas_fuego? 
```

```{r}
# Field Work

## Dendro
dendro_ca_path <- paste0(di, '/data/field_work/dendro/dendro_ca.GPX')
dendro_sj_path <- paste0(di, '/data/field_work/dendro/dendro_sj.GPX')

dendroCA <- readOGR(dendro_ca_path, layer = "waypoints", verbose = FALSE)
dendroSJ <- readOGR(dendro_sj_path, layer = "waypoints", verbose = FALSE)

dendro <- spRbind(dendroCA, dendroSJ)


#### ----- To join the two sites and save as shape 
# not run 
# fw <- dendro[,'name']
# 
# low_ca<- c('B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B09', 'B10',
#          'B26', 'B27', 'B28', 'B29', 'B30')
# low_sj <- c('A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10')
# high_sj<- c('A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20')
# high_ca <- c('B11', 'B12', 'B13', 'B14', 'B15', 'B16', 'B17', 'B18', 'B19', 'B20',
#            'B21', 'B22', 'B23', 'B24', 'B25')
# 
# 
# # Create variable site 
# fw@data$site <- ifelse(fw@data$name %in% low_sj, 'SJ', 
#                        ifelse(fw@data$name %in% high_sj, 'SJ',
#                               ifelse(fw@data$name %in% low_ca, 'CA-Low', 'CA-High')))
# # Variable Loc
# ca <- c(low_ca, high_ca)
# fw@data$loc <- ifelse(fw@data$name %in% ca, "CA", "SJ")
# 
# # Convert to sf 
# dendro_sf <- st_as_sf(fw)
# 
# # Export data as shapefile 
# dendro_path <- paste0(di, '/data/field_work/dendro/dendro_sf.shp')
# 
# sf::st_write(dendro_sf, dsn = dendro_path, layer = "dendro.shp", driver = "ESRI Shapefile")
```


```{r}
# Set spatial extension 
myext <- extent(qp)

mymap <- leaflet() %>%
  fitBounds(myext@xmin, myext@ymin, myext@xmax, myext@ymax) %>% 
  addWMSTiles('http://www.ideandalucia.es/wms/mdt_2005?',
              layers = 'Sombreado_10',
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>', 
              group = 'Hillshade') %>% 
  addTiles(urlTemplate = "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
           attribution = '<a href="https://carto.com/attributions">CARTO</a>',
           group = 'Basemap') %>%

  addWMSTiles('http://www.ideandalucia.es/services/toporaster10/wms?',
              layers = 'toporaster10',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'Topographical') %>%
  addWMSTiles('http://www.ideandalucia.es/wms/mta10r_2001-2013?',
              layers = 'mta10r_2001-2013',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'topo2013') %>% 
  
    addWMSTiles('http://www.ideandalucia.es/wms/mta10v_2007?',
              layers = 'mta10v_2007',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'topo2007') %>% 

  addProviderTiles("Esri.WorldImagery", group='Satellite') %>%
  # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("Hillshade", "Basemap", "Topographical", "Satellite", "topo2013", "topo2007"),
                   overlayGroups = c('Irrigation Channels',
                                     'Natural Protected Area', 
                                     'Quercus pyrenaica forests',
                                     'MOD13Q1 pixels',
                                     "incendios", 
                                     "Actuaciones Forestales", 
                                     "Dendro2016"),
                   options = layersControlOptions(collapsed = TRUE))


```


Distribution map
=======================================================================

```{r}
popup_qp <- paste0("<strong>Population id:</strong> ", qp$POBLACION,
                   "<br><strong>Name:</strong> ", qp$LOCALIDAD,
                   "<br><strong>Valley:</strong> ", qp$VALLE)

popup_iv <- paste0("<strong>Pixel id:</strong> ", modis_iv$id)

popup_acequia <- paste0("<strong>Code:</strong> ", acequias_r$COD_ACEQUI,
                   "<br><strong>Name:</strong> ", acequias_r$NOM_ACEQUI)

popup_fires <- paste0("<strong>Fecha:</strong> ", fires$FECHA)
popup_forestal <- paste0("<strong>Proyecto:</strong> ", forestal_r$cod_proyec)
popup_dendro <- paste0("<strong>Plot id:</strong> ", dendro$name)

mymap %>% 
  addPolylines(data=acequias_r, color='blue', 
               group='Irrigation Channels', weight= 3,
               popup = popup_acequia) %>%
  addPolygons(data = modis_iv,
              group = 'MOD13Q1 pixels',
              fillColor = 'green', fillOpacity = 0.4, color = 'green',
                stroke = TRUE, popup = popup_iv) %>%
  addPolygons(data = qp,
                group= 'Quercus pyrenaica forests',
                fillColor = 'red', fillOpacity = 0.4, 
                stroke = FALSE, popup = popup_qp) %>% 
  addPolygons(data = fires,
                group= 'incendios',
                fillColor = 'orange', fillOpacity = 0.4, 
                stroke = FALSE, popup = popup_fires) %>% 
  addPolygons(data = forestal_r,
                group= 'Actuaciones Forestales',
                fillColor = 'blue', fillOpacity = 0.4, 
                stroke = FALSE, popup = popup_forestal) %>% 
  addPolygons(data = sn, 
              group = 'Natural Protected Area',
              fill=FALSE, color = 'red', weight=2.5) %>% 
  addCircles(data = dendro, 
             group = 'Dendro2016',
             lng=coordinates(dendro)[,'coords.x1'], 
             lat=coordinates(dendro)[,'coords.x2'],
             fill=FALSE, color = 'red', weight=1.5, popup = popup_dendro)
```

